### ISSUE TITLE
Use keychain for storing private key

### ISSUE THREAD

**Issue by simmac** [blizzard4591/openMittsu#11]
The current solution of storing the clients private key in a file in the user directory is, let's be honest, bad, specially in an encryption-focused application.

It would be much better to store the key in the keychain provided by the OS which is usually relatively secure. There is a cross-platform Qt-API which may be useful: https://github.com/frankosterfeld/qtkeychain

**Comment by rugk** [comment]
Hmm, on Windows this is not really secure, but it is better than to store it in plain-text:
> encrypt the password with the user's logon credentials

It is easy to get out the user credentials on Windows if you are an administrator.

**Comment by simmac** [comment]
>It is easy to get out the user credentials on Windows if you are an administrator.

AFAIK you can only reset a users password as an administrator which wouldn't help them (CryptProtectData uses a key derived from the password to encrypt its content).

Even if an administrator could retrieve the key: It is way better than the status quo in which every application with user rights could read the key.

And if that isn't enough, there is still the possibility to encrypt the key with a passphrase-derived KEK (every time the user starts openMittsu, they would have to enter a passphrase) for extra security (like in the Threema app).

**Comment by rugk** [comment]
> AFAIK you can only reset a users password as an administrator

Officially yes, but hey, we talk about Windows here.
See https://github.com/gentilkiwi/mimikatz (e.g. used in [this attack](http://www.heise.de/newsticker/meldung/Bundestags-Hack-Angriff-mit-gaengigen-Methoden-und-Open-Source-Tools-3129862.html) (DE)).

> It is way better than the status quo in which every application with user rights could read the key.

Yes, that's it.

**Comment by blizzard4591** [comment]
With the current update the key is stored in its encrypted form - even if the database itself is not encrypted (QSqlCipher is not available), the key is password protected.

I hope that this is sufficient :)
