### ISSUE TITLE
Sign commits & releases (tags)

### ISSUE THREAD

**Issue by rugk** [blizzard4591/openMittsu#12]
You should consider signing git commits & releases.
- [onionshare#221 (comment)](https://is.gd/7vU4oK)
- It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
- Here is GitHub's help for this: https://help.github.com/articles/generating-a-gpg-key/
- And here is how you can sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by blizzard4591** [comment]
I currently do not own a sufficiently trusted GPG key(set).
All binaries provided by me (i.e. currently only for Windows) are signed using my StartCom Class 2 Code Signing Certificate.
But I will keep this in mind!

**Comment by blizzard4591** [comment]
I started doing this a while back - am I doing it right? If so, please close this issue :)

**Comment by rugk** [comment]
Yeah… :laughing: :+1:
