### ISSUE TITLE
Saving/E-mailing chats

### ISSUE THREAD

**Issue by rinaldosjr** [blizzard4591/openMittsu#13]
Is there any way to save or e-mail the chats?

**Comment by blizzard4591** [comment]
Currently - no.
I am working on a new version that keeps all data (contacts, private key + ID, chats, images, etc.) in a central encrypted storage.
Since I am currently finishing my masters degree, I have little to no time to work on this. Give it a bit of time :)

**Comment by rinaldosjr** [comment]
Take your time! Thanks!
