### ISSUE TITLE
.../format.h:2166:24: error: expected unqualified-id before numeric constant

### ISSUE THREAD

**Issue by ulm** [blizzard4591/openMittsu#19]
Forwarding [Gentoo bug 609366](https://bugs.gentoo.org/609366).

Compilation of Client.cpp fails with:
/var/tmp/portage/net-im/openmittsu-0.9.2_p78/work/openMittsu-0.9.2_p78/3rdparty/spdlog/include/spdlog/details/format.h:2166:24: error: expected unqualified-id before numeric constant
         const unsigned CHAR_WIDTH = 1;

This is caused by the variable name colliding with a macro CHAR_WIDTH defined in limits.h. This was already [reported to spdlog upstream](https://github.com/gabime/spdlog/issues/300) and was [fixed there](https://github.com/gabime/spdlog/commit/6128a87da239228603758fef9dfcb9ea0ab47f3f).

I suggest updating the spdlog submodule to a newer version.

**Comment by blizzard4591** [comment]
Should this not be sufficient, please re-open this issue :)
