### ISSUE TITLE
Conversation not saved

### ISSUE THREAD

**Issue by Lodifice** [blizzard4591/openMittsu#22]
Neither from the current Arch package, nor from a direct build from source it seems to work.

I can sent and receive messages, but as soon as I close the chat tab, they are gone. Of course I would like to be able to read previous messages.

Is this not implemented yet or am I doing it wrong?

Having a conversation history would be a critical feature. Seriously, your work is so great that I am thinking to switch from using the Threema app to openMittsu completely.

**Comment by blizzard4591** [comment]
Thank you for your kind words! I do appreciate this feedback!
You are right, this feature is currently not implemented. I am working on a major rewrite on a lot of the core components, including message history combined with an encrypted storage for configuration plus contacts and history. It is not going as fast as I had hoped, but it will come someday!

**Comment by Lodifice** [comment]
Thanks for the fast answer!

Have you looked at the iOS version of Threema? They store the messages in an sqlite database. Maybe this is also an option for openMittsu. Using the same scheme would allow for easy migration for iOS users. Alternatively you can use the scheme of the Android version, as there exists a script for migrating messages from the iOS to the Android format [0].

How much time do you think it will need? I can't switch to openMittsu until then :D
I don't want to promise too much, but I'll have some spare cycles in August/September, so if you aren't finished by then and you like, I could try to do some of the work by myself.

[0] http://www.noernet.de/IosToAndroid/

**Comment by rugk** [comment]
AFAIK Android uses [sqlcipher](https://github.com/sqlcipher/sqlcipher).

**Comment by mva1985** [comment]
I noticed this problem to just today.  Nice to see that the developer has already been made aware of this.

Also, just want to say how much I appreciate openMittsu

slow and steady is all right!!!

**Comment by blizzard4591** [comment]
This has been fixed with the latest updates!
