### ISSUE TITLE
Contacts Converter

### ISSUE THREAD

**Issue by jstjst** [blizzard4591/openMittsu#23]
I wrote a quick and dirty contact converter that converts the Threema contacts file from a Backup to the openMittsu format:
https://gist.github.com/jstjst/26740217db839e4e655bfb41d56a2fe7

**Comment by rugk** [comment]
Uhh, nice. Actually an one-liner, even.

**Comment by simmac** [comment]
Nice! You just reminded me of my own converter: https://gist.github.com/simmac/917eb7106d9fcf08e1df2cf925afb82a

It's not a one-liner, but it has some options for the appearance of the name

**Comment by jstjst** [comment]
Also nice, as I wrote the appearance wasn't the priority at mine

**Comment by blizzard4591** [comment]
This should be obsolete now - the new release can read and import the Threema .zip Data Backups - I hope it works as intended!
