### ISSUE TITLE
Uncaught Exception: No group…exist, can not manipulate

### ISSUE THREAD

**Issue by sputny** [blizzard4591/openMittsu#28]
Hi all,
i'm running Version: openMittsu_0.9.9plus19-g762a91a-linux-x64-le
without sqlcipher. 
I generate a database from an ID-Backup. It runs smoothly until one of the groups i'm in, gets a message.
The complete error message:
Caught an exception of type InternalErrorException in the main program loop with cause: No group with group ID "xxxxxxxxxxxxxxxx owned by ID XXXXXXXX" exists, can not manipulate.

The program will now terminate.

Thanks to all for contributing to this nice project!!
Kind regards

**Comment by joelfischerr** [comment]
Hi

Have you tried synchronising the group info by asking the group admin to press „Synchronize Group“ in the mobile app?

**Comment by sputny** [comment]
With all other groups that works. But i'm the admin of the group that causes the error.

**Comment by blizzard4591** [comment]
This is a bug and will be fixed soon™. This was broken with the re-write.
