### ISSUE TITLE
Second connect cause exception

### ISSUE THREAD

**Issue by sputny** [blizzard4591/openMittsu#29]
Hi all,
when I start the application(Version: openMittsu_0.9.9plus19-g762a91a-linux-x64-le) I'm able to connect probery. Disconnecting and again connecting, I get the following exception:
Caught an exception of type InternalErrorException in the main program loop with cause: Could not connect signal m_networkSentMessageAcceptor.get()->readyToAcceptMessages() to tryResendingMessagesToNetwork() in /tmp/yaourt-tmp-tobi/aur-openmittsu-git/src/openMittsu-build/src/dataproviders/MessageCenter.cpp  at line 439.

The program will now terminate

Kind regards

**Comment by blizzard4591** [comment]
This should be fixed with the latest commits :) Please test and close the issue if it is.

**Comment by sputny** [comment]
It's fixed. Thanks a lot.
