### ISSUE TITLE
KeePass Auto-Type doesn't work

### ISSUE THREAD

**Issue by OzWT** [blizzard4591/openMittsu#32]
KeePass Auto-Type doesn't work. Tags are considered with "Database password". The password window is added to the custom sequences.
The password window is recognized, because the master password from KeePass is requested, if the KeePass-DB is locked.

Windows 10 x64
KeePass 2.37
openMittsu 0.9.9plus43

**Comment by blizzard4591** [comment]
What exactly does not work for you?
I tried the same configuration and when typing Ctrl + Alt + A in the dialog, it is auto-filled and "okayed".
Do you want KeePass to detect the window when it pops up and auto-fill + confirm it?

I have no experience with Auto-Typing in KeePass (thank you very much for introducing me to this feature btw...).

**Comment by OzWT** [comment]
Sorry for the late reply,
I've tried some different things (new openMittsu version, other "install"-location). And yeah my fault was the location. With openMittsu in "C:\Program Files" Auto-Type doesn't work, and I need admin rights for execution. Now I have it in my portable apps folder (D:\...) and it works how it should, without admin rights and with Two-Channel Auto-Type Obfuscation.
So the issue can be closed.

> Do you want KeePass to detect the window when it pops up and auto-fill + confirm it?

Is this possible? I don't think so, but it would be nice to know, if this is possible.

OT-1: Global Auto-Type is a great feature. Without this, it would only be half as good. I use strg, shift + Y for global Auto-Type, because of better one-handed usability. I think, I can't live without that.

OT-2: Where is the config stored (i.e. location for sqlite-DB)? When I updated to 0.9.9plus44, the DB is found directly by openMittsu.

OT-3: Is it possible to use a DB without password query (or without encryption)? Leaving the password blank doesn't work. I can't load the DB afterwards.

**Comment by rugk** [comment]
You should not (need to run) openmittsu with admin rights in any case.

**Comment by blizzard4591** [comment]
Actually, you needed Admin Rights when OpenMittsu was installed in a privileged location until a few commits ago - because the log file was always written in the Binary Location. This was fixed, so now, you are correct: You should never run OpenMittsu with Admin rights ;)

**Comment by OzWT** [comment]
Thanks for the advice. I will not run openMittsu with admin rights anymore.

> Actually, you needed Admin Rights when OpenMittsu was installed in a privileged location until a few commits ago - because the log file was always written in the Binary Location.

Yes, it doesn't start in "C:\Program Files" (without admin-rights). But now I unzip it in a non-system location (D:\ ...).

May I ask to get a short answer for my off-topic questions 2 and 3?
