### ISSUE TITLE
QT5.10 Cannot mix incompatible Qt library (version 0x50903) with this library (version 0x50a00)

### ISSUE THREAD

**Issue by tiket18** [blizzard4591/openMittsu#35]
the update of the QT 5.10.0-1 libraries has arrived, after that the program crashes right after entering the password from the database.
openMittsu
Logging location: /home/user/.local/share/openMittsu.log
Cannot mix incompatible Qt library (version 0x50903) with this library (version 0x50a00)

Reinstall  openMittsu did not help.

**Comment by blizzard4591** [comment]
You also need to recompile the QSQLCipher plugin - what platform are we talking about, anyway?

If you compiled from source: Recompile QSqlCipher.
If not: Need more information on platform, used method of installation, etc.

Additionally: You should currently **_NOT_** use Qt 5.10.0 - it contains a critical bug in the QSql library.

**Comment by tiket18** [comment]
Exactly, thank you, indeed, with the arriving OT5.10 it was necessary to rebuild libqsqlcipher

yaourt libqsqlcipher

=OK.
