### ISSUE TITLE
native menu bar

### ISSUE THREAD

**Issue by simmac** [blizzard4591/openMittsu#4]
Is there any reason why you are not using the native menu bars? At least in OS X the native menu bar saves spaces and is a de-facto-standard.

See line
`48:    ui.menubar->setNativeMenuBar(false);`
in Client.cpp

**Comment by blizzard4591** [comment]
From the Docs:

> This property specifies whether or not the menubar should be used as a native menubar on platforms that support it. The currently supported platforms are OS X and Windows CE. On these platforms if this property is true, the menubar is used in the native menubar and is not in the window of its parent, if false the menubar remains in the window. On other platforms the value of this attribute has no effect.

Since I do not have Mac OS I do not see a difference between the two options, and so it seems I copied this line from somewhere and never thought about why it is there.

Fixed in 5d0c442630f2aef3898f6635c5275cd034072807.
