### ISSUE TITLE
Emoticon pane too small on KDE Plasma 

### ISSUE THREAD

**Issue by hkramski** [blizzard4591/openMittsu#47]
Just a cosmetic complaint, really like this program:

On KDE Plasma (with default Breeze theme) the emoticon pane is too small and only shows half of the height of the symbols. Can we have the section a little bigger or resizable?

![screenshot_20181106_214559](https://user-images.githubusercontent.com/4007450/48093358-716a9f80-e20f-11e8-8ce8-87c379499665.png)

**Comment by blizzard4591** [comment]
Please test the latest version, it should be fixed (you can grab the border between the widgets and resize).

I am looking forward to your feedback!

**Comment by hkramski** [comment]
Thanks! Works great!
