### ISSUE TITLE
Use proper paths for storing user data/config

### ISSUE THREAD

**Issue by rugk** [blizzard4591/openMittsu#49]
Ref https://threema-forum.de/thread-2024-post-43299.html#pid43299

In short:
* on Windows something like `%AppData%`
* for Linux, see here: https://0x46.net/thoughts/2019/02/01/dotfile-madness/, in short `$XDG_CONFIG_HOME` with a fallback to `$HOME/.config`
* portable mode (as currently done, so it is usable on an USB etc.), can be enabled via a special text file or so in the app's directory

**Comment by blizzard4591** [comment]
What files are currently the problem?
For the log files, I use 
`QStandardPaths::StandardLocation const location = QStandardPaths::AppLocalDataLocation;`

to build the proper path. I hope this works. If not, an error message should be displayed through std::cerr.
For the settings, I use the default constructor for QSettings() (https://doc.qt.io/qt-5/qsettings.html) and that seems to imply the NativeFormat, which on Windows is the registry. 
On my machine, my options are saved under HKEY_CURRENT_USER\Software\openMittsu\OpenMittsu\options. This should not require admin rights.

I will look into this more, but if you have a pointer or ideas what the problem might be, that would be nice.

Also: Is Native/registry not a good choice? Sure, for portable maybe not, but storing them locally next to the binary is even worse for UAC.

**Comment by rugk** [comment]
Okay, so actually looks good. Just wonder why the forum user had issues then. So probably better discuss/debug this in the forum thread.
