### ISSUE TITLE
Provide builds for macOS

### ISSUE THREAD

**Issue by ddobrev** [blizzard4591/openMittsu#56]
Possible solutions are AppVeyor or Travis which offer free CI and deployment for open source.

**Comment by blizzard4591** [comment]
This project is using Travis and I tried building for MacOS, but I do not have access to a Mac and the Travis build is broken somehow and I could not figure it out "remotely", so after I while I gave up.

If you can provide help, I'd be happy to accept the fixes.

There are brew recipes (see https://github.com/blizzard4591/homebrew-qt5-sqlcipher and https://github.com/blizzard4591/homebrew-openMittsu) but they require some testing/fixing.

**Comment by ddobrev** [comment]
I understand, thank you for your reply. Could you please send me the link to your Travis? I might be able to notice something to help you out.

**Comment by rugk** [comment]
https://travis-ci.org/blizzard4591/openMittsu

**Comment by ddobrev** [comment]
@rugk thank you. @blizzard4591 I'm a little confused – the build at this link is all green. Where's the error you've mentioned?

**Comment by rugk** [comment]
build removed again, see https://github.com/blizzard4591/openMittsu/search?q=Mac+OS&type=Commits

**Comment by ddobrev** [comment]
@rugk OK. Next: where do I find this `macOsPackage.sh`?

**Comment by ddobrev** [comment]
I've found the script but I cannot quite understand it, it used some patched Python version of `macdeployqt`. I'm not sure when I can test in more detail so what would you say about the following in the meantime: make Travis upload an archive of the compiled binaries so that people can use `macdeployqt` on their own to generate DMG-s?

**Comment by ddobrev** [comment]
@blizzard4591 @rugk I may have found the problem. As far as I can see, [you build with CMake ](https://github.com/blizzard4591/openMittsu/blob/master/travis/build.sh#L16) which I'm not sure bundles the application by itself. You might have to add a few lines for macOS using [these CMake functions](https://cmake.org/cmake/help/v3.16/module/BundleUtilities.html).
Please let me know if you have the opportunity to try them yourselves.

**Comment by ddobrev** [comment]
Please, I'm asking you to continue this discussion. I'm considering purchasing an ID from Threema but it would only be useful to me with a working desktop client for macOS. I would like to at the very least know it can actually run. So let me know what you think about my suggestion above.

**Comment by rugk** [comment]
Remember there is also [Threema Web](https://threema.ch/threema-web) that you can use on any desktop device.

As for myself, I am just a contributor here. We have to wait for @blizzard4591 to answer. 😃

**Comment by ddobrev** [comment]
@rugk thank you for your reply and for mentioning Threema Web even though I was already aware of it. My problem with it is that find it too inconvenient to keep an open browser just because of a messenger, and its performance in general. This is why I need a stand-alone native client such as this one.
@blizzard4591 please comment whenever you can – do you think my suggestion could resolve the failing macOS build?

**Comment by blizzard4591** [comment]
Sorry, I am on this issue, I was/am just busy with work.
I currently have access to an old MacMini (or something like that, I have no clue about Macs) and will try the build process there. 

I know that @PKizzle managed to compile successfully with homebrew, I will try fixing the remaining issues. As far as I remember, there was this macdeployqt script which was supposed to bundle everything, but it has been some time since I looked into this.

Currently, notifications are not supported (natively). I started looking into this, but at the time there was no true cross-platform alternative, so I stopped looking into it. If you are willing to implement the Mac-specific parts (there is just one or two functions in Client.cpp that would need to be adapted), I would happily merge it.

**Comment by ddobrev** [comment]
Thank you very much for working on this, @blizzard4591 . I hope my suggestion can be a useful clue to you. If you manage to upload regular DMG-s, this would be absolutely outstanding.

I might be able to help with the native notifications but I would first need some answers by you, please:
1. Do you have any notifications at present and how do they work (a screen-shot from your Mac would be most useful)?
2. What trouble have you encountered with `Snorenotify` on Windows? Have you tried its latest version to check if the trouble persists?

If I think of anything else, I'll ask. Sleep well.

**Comment by ddobrev** [comment]
@blizzard4591 thank you for your new work, I'm happy to see the project moving forward. :) Please tell me, though: have you been able to produce packages for macOS with your Mac Mini or otherwise?

**Comment by blizzard4591** [comment]
Sorry, I was busy.
@ddobrev Could you check out https://downloads.openmittsu.de/dmg/openmittsu.dmg?
Does this work?

**Comment by ddobrev** [comment]
@blizzard4591 thank you! The application starts (lacks an icon) and I can go through the wizard, no issues. This is all I can test so far, though, because I haven't purchased a Threema ID. I'm waiting for a functional desktop client in order to do so - a little chicken and egg. :) Finally, one more issue is that the application closes when I press the 'x'  - on macOS applications should instead hide in the dock and then be restored through it.

**Comment by ddobrev** [comment]
However, since this issue in particular only concerns builds for macOS, you may consider it successfully resolved.

**Comment by ddobrev** [comment]
@blizzard4591 now that you have working builds for macOS, you could add links to https://www.openmittsu.de/ so that more people know about it.

**Comment by blizzard4591** [comment]
Its now mentioned on the homepage: https://www.openmittsu.de/downloads.html

**Comment by ddobrev** [comment]
@blizzard4591 excellent! I hope you now get many new users. 🙂
