### ISSUE TITLE
ID backups do not work

### ISSUE THREAD

**Issue by fynngodau** [blizzard4591/openMittsu#59]
When I generate an ID backup using the menu in openMittsu (Database → Create Backup…) and enter the generated code as well as the chosen password in Threema Android, the Restore button is disabled (grayed out). I tried the latest version, version 2.9 as well as an even older version with the same result. The generated ID works for creating a new openMittsu database.

**Comment by blizzard4591** [comment]
Hmm, I fear I can not reproduce this issue. I have not changed anything in this part of the implementation for a long time, so it should not be a change on my end.

To test, I created a new backup using openMittsu 0.9.15+1 and imported it into Threema for Android (the most recent APK I had, 4.something) and it worked without issue. That the button was disabled - was there maybe a space where none belong?

**Comment by fynngodau** [comment]
Aha, I entered the code manually (instead of generating and scanning a QR code with external software) and the button was not grayed out this time. There must have been some invisible forbidden character somewhere, but I couldn't quite figure out what it was.

Thank you!
