### ISSUE TITLE
Request command line option: SQLCipher-Warning

### ISSUE THREAD

**Issue by fsatzger** [blizzard4591/openMittsu#63]
I built openMittsu without QSQLCipher (using the provided CMake-Option, because QSQLCipher was not compilable on my machine without bigger issues) and I'd like to get rid of the warning at startup so that I can run openMittsu on system startup.

**Comment by blizzard4591** [comment]
Hmm, I can add the option, but I would rather help you set up QSQLCipher, because we will fix issues for everybody else on the way - if you are open to that, could you tell me what went wrong?

**Comment by fsatzger** [comment]
To be honest, I didn't work really hard on that topic, because I already lost many hours getting the whole thing running at all. Biggest issue: the stretch binaries didn't work for Mint 18 although it's loosely based on stretch so I decided to build it by myself (for now, I wrote a little workaround for this topic by myself).

I'm a bit short on time atm, but perhaps I can support the search for errors.

Starting point: (I suppose you're not German, so basically it says qsqlcachedresult_p.h not found) - at that point I instantly stopped searching because I don't need database encryption here.

```
qt5-sqlcipher $ make
[ 11%] Automatic MOC for target qsqlcipher
[ 11%] Built target qsqlcipher_autogen
[ 22%] Building CXX object CMakeFiles/qsqlcipher.dir/qt-file-cache/5.6.1/qsql_sqlite.cpp.o
/home/tornado/Downloads/openMittsu/qt5-sqlcipher/qt-file-cache/5.6.1/qsql_sqlite.cpp:43:46: fatal error: QtSql/private/qsqlcachedresult_p.h: Datei oder Verzeichnis nicht gefunden
compilation terminated.
CMakeFiles/qsqlcipher.dir/build.make:108: die Regel für Ziel „CMakeFiles/qsqlcipher.dir/qt-file-cache/5.6.1/qsql_sqlite.cpp.o“ scheiterte
make[2]: *** [CMakeFiles/qsqlcipher.dir/qt-file-cache/5.6.1/qsql_sqlite.cpp.o] Fehler 1
CMakeFiles/Makefile2:117: die Regel für Ziel „CMakeFiles/qsqlcipher.dir/all“ scheiterte
make[1]: *** [CMakeFiles/qsqlcipher.dir/all] Fehler 2
Makefile:171: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

```

**Comment by fsatzger** [comment]
Update:
I invested some time in seaching for a solution and found it:
My system was missing the development package **qtbase5-private-dev**. Also, `make install` copied the plugin the system local folder (usr/local/lib/...), which is right by means of the filesyste hierarchy standard but doesn't work out of the box in many distros...

Despite that, I'd still vote for having a command line option for that.

**Comment by blizzard4591** [comment]
The package is mentioned here: https://github.com/blizzard4591/qt5-sqlcipher/ and in Step 4 of the openMittsu How-to-Build: https://github.com/blizzard4591/openMittsu#general-steps

The install location should be automatically determined by a CMake test (see CMake output "Determined plugin folder:") from the Qt plugin system. 

If it does not work, i.e. does not point to the right location, please send me the location of e.g. "libqsqlite.so" and what the CMake output says about the determined plugin folder!

**Comment by fsatzger** [comment]
Seems that this doesn't work the right way:
```
-- Added  to link directories...
-- Found Qt5 version 5.6.1.
-- Using cached/shipped versions of required header/source files.
-- Determined plugin folder: /usr/lib/x86_64-linux-gnu/qt5/plugins/sqldrivers
-- Stripped plugin path to lib/x86_64-linux-gnu/qt5/plugins from /usr/lib/x86_64-linux-gnu/qt5/plugins
-- Configuring done
-- Generating done
```
...
```
[ 11%] Automatic MOC for target qsqlcipher
[ 11%] Built target qsqlcipher_autogen
[ 55%] Built target qsqlcipher
[ 66%] Automatic MOC for target qsqlcipher-test
[ 66%] Built target qsqlcipher-test_autogen
[100%] Built target qsqlcipher-test
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/x86_64-linux-gnu/qt5/plugins/sqldrivers/libqsqlcipher.so

```
