### ISSUE TITLE
Configuration broken after cancelling database password entry

### ISSUE THREAD

**Issue by fsatzger** [blizzard4591/openMittsu#64]
When starting openMittsu with a working configuration but press "cancel" on database password entry and quit the application afterwards, the database path gets deleted from the config file.

While this is consequential from programmatical view (no open database on application quit), I think that's not the behaviour end users would expect.

**Comment by blizzard4591** [comment]
My argument is that when the user cancels opening the database, the program should not try to get him to open the same database again. You can of course open it again manually, but shoving it in your face again seems bad. Opinion?

**Comment by fsatzger** [comment]
That's of course a prefectly valid design decision you made :)

Usually the whole thing shouldn't bother any user at all, it only came up because I accidentially started multiple instances as result of issue #62. Cancelling and quitting those instances (but letting the one with right DB open) lead to the "first-use wizard" at the following system startup. Took me a while to find out why.

I myself would not expect the software to lose its DB only because I clicked cancel for the password entry but as I said, seen from the aspect that there's no DB open I can understand why you did it that way.

**Comment by blizzard4591** [comment]
You are right. I added a dialog that asks the user before removing the path :)

**Comment by fsatzger** [comment]
perfect solution ;)
