### ISSUE TITLE
Missing dependencies in Ubuntu 20.04 / Focal

### ISSUE THREAD

**Issue by HorstBaerbel** [blizzard4591/openMittsu#65]
Installing the .deb according to the README tells me libqt5sql5-sqlcipher, libqrencode3 and libavcodec-extra are missing and not installable. Not sure if the instructions are still correct. Loading the AppImage it tells me an update (https://downloads.openmittsu.de/deb/openmittsu_0.9.15-10_amd64.deb) is available, but the .deb it downloads then is also not installable due to missing packages.

**Comment by blizzard4591** [comment]
Oof, yeah the dependency management of the debs currently is a mess. I had build-VMs in the past for some versions of Ubuntu and Debian, but it was a pain to maintain, so I didn't.

What would the correct dependencies for 20.04 or even 20.10 be?

**Comment by HorstBaerbel** [comment]
Using ThreemaQT instead now. Comes as a flatpak with everything needed...
