### ISSUE TITLE
Unknown Message Flag Bits are set. Crash. 

### ISSUE THREAD

**Issue by gghs5524** [blizzard4591/openMittsu#68]
Hello. Debian 10. openMittsu closes when a message is sent from the Threema.ch site (threema gateway).
Now, every time when I trying to connect to the account, the app immediately crashes. Please tell me how to fix it.
The logs contain the following errors.

```
[main] [warning] Can not display MessageBox for Exception Handling: Not in main GUI thread.
[main] [critical] Caught an exception of type IllegalArgumentExceptionImpl in the main program loop with cause: : Unknown Message Flag Bits are set: ffffffffffffff**
Caught an exception of type IllegalArgumentExceptionImpl in the main program loop with cause:: Unknown Message Flag Bits are set: ffffffffffffff**
[main] [critical] Since the worker thread just terminated, everything will close now.
QSqlDatabasePrivate::removeDatabase: connection 'openMittsuDatabaseConnection**' is still in use, all queries will cease to work.
QObject::killTimer: Timers cannot be stopped from another thread
QObject::~QObject: Timers cannot be stopped from another thread

```

**Comment by blizzard4591** [comment]
Thanks for reporting this issue!
Since I currently have no access to Threema Gateway, I can not test this directly. I have asked Threema for support (I want to implement/support the new protocol features), but this could take a moment to do.

In the meantime, if you compile openMittsu yourself I can tell you how to disable the crashing, I could also push this as a general change (also I am unsure if this would be the right way to do it).

If possible, reach out to me at `mail@openmittsu.de`, I can send you my Threema ID and you could send Gateway messages there for me to see the issue myself.

**Comment by gghs5524** [comment]
> Thanks for reporting this issue!
> Since I currently have no access to Threema Gateway, I can not test this directly. I have asked Threema for support (I want to implement/support the new protocol features), but this could take a moment to do.
> 
> In the meantime, if you compile openMittsu yourself I can tell you how to disable the crashing, I could also push this as a general change (also I am unsure if this would be the right way to do it).
> 
> If possible, reach out to me at `mail@openmittsu.de`, I can send you my Threema ID and you could send Gateway messages there for me to see the issue myself.

Thanks for the answer.
You can register here - https://gateway.threema.ch/en
In your client area, it is possible to send messages (free of charge) to a certain ID, and such messages cause crash. Please tell me how to fix this if I'm doing the compilation myself?
Now I just can't use my account, as it immediately flies out.

**Comment by blizzard4591** [comment]
Ah, did not intend to close right away. But please test the current version, this should prevent the crashes :)

**Comment by gghs5524** [comment]
> Ah, did not intend to close right away. But please test the current version, this should prevent the crashes :)

Re-compiled. Unfortunately it still doesn't work. The same errors...

**Comment by blizzard4591** [comment]
I identified and fixed one more bug and could successfully receive your message. Could you verify that it works for you as well?

**Comment by gghs5524** [comment]
> I identified and fixed one more bug and could successfully receive your message. Could you verify that it works for you as well?

Thanks! It works.
