### ISSUE TITLE
installation issues on armhf

### ISSUE THREAD

**Issue by huggymann** [blizzard4591/openMittsu#74]
Trying to install on armhf throws a dependencies error. I have been using the method mentioned in the download section using command line (apt) but also the deb package installation fails. 

Error Message manual steps

> The following packages have unfulfilled dependencies:
> openmittsu : Depends on: libqt5sql5-sqlcipher but is not installable.
>              Depends on: libqrencode3 but is not installable
>              Depends on: libavcodec-extra

Error Message deb package installation:
![image](https://user-images.githubusercontent.com/61777949/111275585-991b6f00-8636-11eb-9474-a681dbd71b34.png)

my system information 
- Raspberry pi 3 
- raspbian

**Comment by blizzard4591** [comment]
Sorry about this issue, the dependencies for the packages have not been maintained very well.
There are two issues here:

1. libqrencode3 is missing: I fixed this by changing the depends stance to libqrencode4.
2. libqt5sql5-sqlcipher: You need to install this by hand, its available from the same source: https://downloads.openmittsu.de/deb/libqt5sql5-sqlcipher_0.1.3-1-5.11.3_armhf.deb

My build server is rebuilding the openMittsu package for ArmHF, but even on my RPIv4, a full build takes 1:10h.
Once it is done, you can find the (hopefully) fixed DEB here: https://downloads.openmittsu.de/deb/openmittsu_0.9.16-15_armhf.deb
