### ISSUE TITLE
iOS-app created Group: name not set (group sync unanswered) and other issues

### ISSUE THREAD

**Issue by gyps** [blizzard4591/openMittsu#76]
Dear all,

I just switched to a new ID for using openMittsu instead of my smartphone Threema Android app. 

When group admins add my new ID to their group, the openMittsu Client seems to ask for a group sync, that is unanswered. Somehow I'm not able to reproduce this behaviour myself. If I create a group on my android phone and add my openMittsu-ID to it everything works fine. 

Can this have to do with the version of the client-app the group admin uses? Or iOS vs. Android?

Cheers,
Alex

**Comment by gyps** [comment]
There are even more issues if the group is created/administered by an iOS-app account/client.
1. iOS sent messages don't appear at all in the group chat
2. messages sent to the group are not displayed in iOS

My test-setup was using three ID's with three clients (iOS, Android, openMittsu (yesterday's git-version))
Android can communicate with both but iOS fail to communicate with each other via group
Direct communication (not using groups) between iOS and openMittsu works fine.

**Comment by blizzard4591** [comment]
Hi Alex, that sounds interesting!
I do not have access to an iOS client/phone, so I can not test this myself.
Are you using a debug build (cmake -DCMAKE_BUILD_TYPE=Debug -DOPENMITTSU_DEBUG=On)?
I think to dive deeper into this issue, we need to look at the log, or you can include one of my IDs in the testing.
Contact me at mail@openmittsu.de for exchanging IDs and/or the log - be careful not to post a full debug log here as it contains a lot of potentially personal details.

**Comment by gyps** [comment]
Just noticed that there are tons of error messages in the shell I started openMittsu in. All of the form:
[2021-04-11 13:35:46.389] [main] [critical] Unknown error while parsing payload of received message from [...] with ID [...] : /home/aster/src/openMittsu/src/crypto/EncryptionKey.cpp:18: Size of Encryption Key is 24 Bytes instead of 32 Bytes.

**Comment by blizzard4591** [comment]
Is there anything leading up to the errors? Is it parsing specific message types?
