### ISSUE TITLE
Unable to enter anything as "Backup" filename

### ISSUE THREAD

**Issue by hkramski** [blizzard4591/openMittsu#8]
Trying to load an existing backup with "Identity / Load Backup..." but the "Backup" input field neither accepts clipboard contents nor ordinary keystrokes.

This program uses Qt version 5.6.1.
Version: 0.9.2 (+53 commits) build from revision gec6867e.
Compiled on Linux 4.6.2-1-ARCH using compiler version GCC 6.1.1.

**Comment by hkramski** [comment]
Oops, got it... The very long code of an ID backup is required here, not a file name of a data backup. (Did a complete data backup first.)

**Comment by blizzard4591** [comment]
This happens too often, I will probably change the wizard and add an example.
