### ISSUE TITLE
Ambiguous error message: "Could not connect to server."

### ISSUE THREAD

**Issue by pingberlin** [blizzard4591/openMittsu#82]
Since today I'm getting the following error message in my client:

```
[2021-12-03 13:37:04.057] [main] [warning] Could not connect to server. The error was: The host was not found. Please check the host name and port settings.
```

While the reason for the error might be on might side, I can not diagnose it further on my own.

Could you please include the host name and port in the error message?

Thanks 🙇

**Comment by blizzard4591** [comment]
I added that to the message, but my guess is that you are using an older version which still uses (or rather, tries to use) the proxy server that Threema installed specifically for openMittsu. We decided to get rid of this, I changed openMittsu to use the same servers as the App and they shut it down one or two days ago. 

Try updating first!

**Comment by pingberlin** [comment]
Thanks. That fixed it :)
